
# biodata onlin
print ("=====input bioadat online=====")
nama = input ("masukkan nama:")
panggilan = input ("masukkan nama panggilan :")
tanggal  = input ("tempat tanggal lahir     : ")
alamat  = input ("alamat lengkap            : ")
kelamin = input ("jenis kelamin             : ")
agama = input ("agama                       : ")
telpon = input (" no telpon                 :")
email = input ("email                       : ")
bb  = input ( " bb & tinggi badan           :")
hobi = input ( "hobi                        : ")
smp = input (" asal smp                     :")
medsos = input (" nama medsos ig            : " )
tiktok = input (" nama medsos tiktok        : ")
alasan = input (" alasan masuk telkom       : ")
harapan = input ( " harapan masuk telkom    :" )
        
print  ("masukkan nama          :" , nama)
print  ("masukkan nama panggilan: " , panggilan)
print  ("tempat tanggal lahir   : " , tanggal)
print  ("alamat lengkap         : " , alamat)
print  ("jenis kelamin         : " , kelamin)
print  ("agama                  : " , agama)
print  ("no telpon             :" , telpon)
print  ("email                  : " , email)
print  ("bb & tinggi badan    :", bb)
print  ("hobi                  : " , hobi)
print  ("asal smp              :", smp)
print  ("nama medsos ig        : ", medsos )
print  ("nama medsos tiktok    : ", tiktok)
print  ("alasan masuk telkom   : ", alasan)
print  ("harapan masuk telkom :", harapan )
